spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown=timeout: 0

  mail:
    host: smtp.163.com
    username: guwy16@163.com
    password: GUIBWHPESDRFKBMS
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: com.gggsl.*.entity
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.gggsl.common.dao.BaseDao
  not-empty: true
  identity: MYSQL
  style: camelhumpAndUppercase
  before: true


pagehelper:
  helperDialect: mysql
  reasonable: true
  params: countSql
  support-methods-arguments: true

cache: redis

orc:
  #baidu
  grant_type: "client_credentials"
  client_id: "M16Nw2U3lRQ8rTojgEWTOGFg"
  client_secret: "ecjykwekG1ZBHj1QRHI9XmyQaBNsx9PV"

  #chajiying
  user: simklot
  pass: qwaa1976
  softid: 903833
  len_min: 0
  codetype: 1005



  #logging:
  #level:
  #com.qisheng.mgjcrm.dao : debug
  #config: classpath:log4j.properties # 指定log4j配置文件的位置

